services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - splash
    stdin_open: true
    tty: true

  splash:
    image: scrapinghub/splash:latest
    ports:
      - "8050:8050"
